import 'package:hive/hive.dart';

part 'budget_model.g.dart'; // This will be generated by Hive

@HiveType(typeId: 1) // Use a unique typeId (different from Expense)
class Budget {
  @HiveField(0)
  final double amount;

  Budget(this.amount);
}